/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QuizLessonIdRouteImport } from './routes/quiz.$lessonId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CheckoutCourseIdRouteImport } from './routes/checkout.$courseId'
import { Route as CertificateCourseIdRouteImport } from './routes/certificate.$courseId'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSlidesRouteImport } from './routes/admin.slides'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const QuizLessonIdRoute = QuizLessonIdRouteImport.update({
  id: '/quiz/$lessonId',
  path: '/quiz/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCourseIdRoute = CheckoutCourseIdRouteImport.update({
  id: '/checkout/$courseId',
  path: '/checkout/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCourseIdRoute = CertificateCourseIdRouteImport.update({
  id: '/certificate/$courseId',
  path: '/certificate/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlidesRoute = AdminSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slides': typeof AdminSlidesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/certificate/$courseId': typeof CertificateCourseIdRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/p/$slug': typeof PSlugRoute
  '/quiz/$lessonId': typeof QuizLessonIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slides': typeof AdminSlidesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/certificate/$courseId': typeof CertificateCourseIdRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/p/$slug': typeof PSlugRoute
  '/quiz/$lessonId': typeof QuizLessonIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slides': typeof AdminSlidesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/certificate/$courseId': typeof CertificateCourseIdRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/p/$slug': typeof PSlugRoute
  '/quiz/$lessonId': typeof QuizLessonIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/books'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/profile'
    | '/register'
    | '/services'
    | '/support'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/slides'
    | '/admin/students'
    | '/admin/testimonials'
    | '/certificate/$courseId'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/p/$slug'
    | '/quiz/$lessonId'
    | '/admin/'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/profile'
    | '/register'
    | '/services'
    | '/support'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/slides'
    | '/admin/students'
    | '/admin/testimonials'
    | '/certificate/$courseId'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/p/$slug'
    | '/quiz/$lessonId'
    | '/admin'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/books'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/profile'
    | '/register'
    | '/services'
    | '/support'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/slides'
    | '/admin/students'
    | '/admin/testimonials'
    | '/certificate/$courseId'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/p/$slug'
    | '/quiz/$lessonId'
    | '/admin/'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BooksRoute: typeof BooksRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyCoursesRoute: typeof MyCoursesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  WishlistRoute: typeof WishlistRoute
  CertificateCourseIdRoute: typeof CertificateCourseIdRoute
  CheckoutCourseIdRoute: typeof CheckoutCourseIdRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
  PSlugRoute: typeof PSlugRoute
  QuizLessonIdRoute: typeof QuizLessonIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/quiz/$lessonId': {
      id: '/quiz/$lessonId'
      path: '/quiz/$lessonId'
      fullPath: '/quiz/$lessonId'
      preLoaderRoute: typeof QuizLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$courseId': {
      id: '/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof CheckoutCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$courseId': {
      id: '/certificate/$courseId'
      path: '/certificate/$courseId'
      fullPath: '/certificate/$courseId'
      preLoaderRoute: typeof CertificateCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slides': {
      id: '/admin/slides'
      path: '/slides'
      fullPath: '/admin/slides'
      preLoaderRoute: typeof AdminSlidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlidesRoute: typeof AdminSlidesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlidesRoute: AdminSlidesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BooksRoute: BooksRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyCoursesRoute: MyCoursesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  WishlistRoute: WishlistRoute,
  CertificateCourseIdRoute: CertificateCourseIdRoute,
  CheckoutCourseIdRoute: CheckoutCourseIdRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
  PSlugRoute: PSlugRoute,
  QuizLessonIdRoute: QuizLessonIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
