ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS what_will_learn TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS target_audience TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS duration_hours INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duration_minutes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS materials_included TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS requirements TEXT DEFAULT '';